basic working
oruchkin/Async_API_sprint_3 pull request #92
Opened 2024-08-04 19:27 UTC by oruchkin

уже работает в кликхаус значения доходят из UGC, но еще не готово

2024-08-04 22:49 UTC, GDreyV requested changes

2024-08-04 22:49 UTC, GDreyV commented on ugc/docker-compose.yml
> +version: '3.5'
А для чего два одинаковых docker-compose файла?

2024-08-04 22:49 UTC, GDreyV commented on ugc/etl_service/src/clickhouse_client.py
> +    def insert_data(self, data):
Добавь типы, плиз. Я так предполагаю, что data должен быть list, т.к. из кафки оно достается пачками, тогда дальше не надо data отдельно оборачивать в array

2024-08-04 22:49 UTC, GDreyV commented on ugc/etl_service/src/kafka_consumer.py
> +        for message in self.consumer:
Я надеюсь, оно тут не по одному сообщения идет?

2024-08-04 22:49 UTC, GDreyV commented on ugc/etl_service/src/kafka_consumer.py
> +            enable_auto_commit=True,
Оно должно быть False, это обсуждали на созвоне, что коммит надо делать поле того, как данные были сохранены в кликхаусе

2024-08-05 12:19 UTC, GDreyV commented on ugc/docker-compose.yml
> +version: '3.5'
Их надо создать, вот тут описано как https://github.com/oruchkin/Async_API_sprint_3/blob/main/README.md#external-volumes

2024-08-05 19:13 UTC, oruchkin commented on ugc/docker-compose.yml
> +version: '3.5'
docker compose по умолчанию должен запускаться одной командой:

```docker-compose up```

задумка такая что руками пользователь ничего не делает, и даже не думает о том что в yaml файле написано 
external это история скорее для ```docker-compose.dev.yml```

2024-08-07 19:56 UTC, oruchkin commented on ugc/etl_service/src/kafka_consumer.py
> +            enable_auto_commit=True,
сделано 👍

2024-08-07 19:56 UTC, oruchkin commented on ugc/etl_service/src/kafka_consumer.py
> +        for message in self.consumer:
сделано 👍

2024-08-07 19:56 UTC, oruchkin commented on ugc/etl_service/src/clickhouse_client.py
> +    def insert_data(self, data):
сделано 👍

2024-08-07 20:40 UTC, GDreyV commented on ugc/etl_service/src/kafka_consumer.py
> +        for message in self.kafka_consumer:
Может что-то типа https://stackoverflow.com/questions/76246744/confluent-kafka-consumer-batch-consuming ? Этот код очень странный - мы ничего не коммитим пока не наберется нужное количество сообщений, это очень странный подход.

2024-08-07 21:31 UTC, GDreyV commented on ugc/etl_service/src/kafka_consumer.py
> +        max_messages_to_fetch = 100000
`100_000`, добавь подчеркивание, чтобы можно было читать

2024-08-07 21:31 UTC, GDreyV commented on ugc/docker-compose.yml
> -services:
Файл должен быть именно `docker_compose.yaml`, не '.yml`

2024-08-07 21:31 UTC, GDreyV commented on ugc/etl_service/src/clickhouse_client.py
> +    def insert_data(self, data: List):
Тип `list`, `List` это устаревшее. И list чего?

2024-08-07 21:31 UTC, GDreyV commented on ugc/etl_service/src/kafka_consumer.py
> +        logging.basicConfig(level=logging.INFO)
Почему оно тут? Это же настройка глобального логгера, оно должно быть где-то в корне

2024-08-07 21:31 UTC, GDreyV commented on ugc/etl_service/src/kafka_consumer.py
> +                self.kafka_consumer.commit()
Я бы тут какой-нибудь лог добавил, что оно вообще работает

2024-08-07 21:41 UTC, merged